spring.application.name=bakend_vape

spring.datasource.url=jdbc:postgresql://localhost:5433/shop_vape
spring.datasource.username=postgres
spring.datasource.password=loza
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
spring.flyway.validate-on-migrate=true
spring.flyway.out-of-order=true

app.upload.dir=uploads/imagenes
spring.web.resources.static-locations=file:uploads/

spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

# VIP thresholds
vip.pedidos.minimos=10
vip.antiguedad.meses=12
vip.inactividad.meses=12