CREATE TABLE atributo
(
    id_atributo BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    nombre      VARCHAR(100)                            NOT NULL,
    unidad      VARCHAR(50),
    created_at  TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    updated_at  TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_atributo PRIMARY KEY (id_atributo)
);

CREATE TABLE auditoria
(
    id_auditoria   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    id_usuario     BIGINT                                  NOT NULL,
    accion         VARCHAR(20)                             NOT NULL,
    tabla          VARCHAR(100)                            NOT NULL,
    registro_id    BIGINT                                  NOT NULL,
    valor_anterior TEXT,
    valor_nuevo    TEXT,
    fecha          TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    CONSTRAINT pk_auditoria PRIMARY KEY (id_auditoria)
);

CREATE TABLE avisos
(
    id_aviso     BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    titulo       VARCHAR(150)                            NOT NULL,
    descripcion  TEXT,
    solo_vip     BOOLEAN                                 NOT NULL,
    fecha_inicio TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    fecha_fin    TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    id_usuario   BIGINT                                  NOT NULL,
    created_at   TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    updated_at   TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_avisos PRIMARY KEY (id_aviso)
);

CREATE TABLE carrito
(
    id_carrito BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    id_usuario BIGINT,
    session_id VARCHAR(128),
    activo     BOOLEAN                                 NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    updated_at TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_carrito PRIMARY KEY (id_carrito)
);

CREATE TABLE carrito_producto
(
    id_carrito_producto BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    id_producto         BIGINT                                  NOT NULL,
    id_carrito          BIGINT                                  NOT NULL,
    cantidad            INTEGER                                 NOT NULL,
    precio_venta        DECIMAL(10, 2)                          NOT NULL,
    subtotal            DECIMAL(10, 2)                          NOT NULL,
    created_at          TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    updated_at          TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_carrito_producto PRIMARY KEY (id_carrito_producto)
);

CREATE TABLE categoria
(
    id_categoria BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    nombre       VARCHAR(100)                            NOT NULL,
    created_at   TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    updated_at   TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_categoria PRIMARY KEY (id_categoria)
);

CREATE TABLE direccion
(
    id_direccion BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    direccion    VARCHAR(255),
    referencia   VARCHAR(255),
    principal    BOOLEAN                                 NOT NULL,
    id_usuario   BIGINT,
    created_at   TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    updated_at   TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_direccion PRIMARY KEY (id_direccion)
);

CREATE TABLE imagen
(
    id_imagen  BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    url        VARCHAR(255)                            NOT NULL,
    nombre     VARCHAR(255)                            NOT NULL,
    estado     BOOLEAN                                 NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    updated_at TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_imagen PRIMARY KEY (id_imagen)
);

CREATE TABLE imagen_categoria
(
    id_imagen_categoria BIGINT                      NOT NULL,
    id_imagen           BIGINT                      NOT NULL,
    id_categoria        BIGINT                      NOT NULL,
    created_at          TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    updated_at          TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_imagen_categoria PRIMARY KEY (id_imagen_categoria)
);

CREATE TABLE imagen_producto
(
    id_imagen_producto BIGINT                      NOT NULL,
    id_imagen          BIGINT                      NOT NULL,
    id_producto        BIGINT                      NOT NULL,
    created_at         TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    updated_at         TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_imagen_producto PRIMARY KEY (id_imagen_producto)
);

CREATE TABLE marcas
(
    id_marca   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    nombre     VARCHAR(100)                            NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    updated_at TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_marcas PRIMARY KEY (id_marca)
);

CREATE TABLE movimiento_puntos
(
    id_movimiento_puntos BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    id_usuario           BIGINT                                  NOT NULL,
    puntos               INTEGER                                 NOT NULL,
    motivo               VARCHAR(50)                             NOT NULL,
    referencia_id        BIGINT,
    created_at           TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    updated_at           TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_movimiento_puntos PRIMARY KEY (id_movimiento_puntos)
);

CREATE TABLE ofertas_subasta
(
    id_oferta_subasta BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    id_subasta        BIGINT                                  NOT NULL,
    id_usuario        BIGINT                                  NOT NULL,
    monto             DECIMAL(10, 2)                          NOT NULL,
    created_at        TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    updated_at        TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_ofertas_subasta PRIMARY KEY (id_oferta_subasta)
);

CREATE TABLE pedido_producto
(
    id_pedido_producto BIGINT                      NOT NULL,
    pedido_id          BIGINT                      NOT NULL,
    producto_id        BIGINT                      NOT NULL,
    cantidad           INTEGER                     NOT NULL,
    precio_unitario    DECIMAL(10, 2)              NOT NULL,
    subtotal           DECIMAL(10, 2)              NOT NULL,
    created_at         TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    updated_at         TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_pedido_producto PRIMARY KEY (id_pedido_producto)
);

CREATE TABLE pedidos
(
    id_pedido  BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    id_usuario BIGINT                                  NOT NULL,
    total      DECIMAL(10, 2)                          NOT NULL,
    fecha      TIMESTAMP WITHOUT TIME ZONE,
    estado     BOOLEAN                                 NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    updated_at TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_pedidos PRIMARY KEY (id_pedido)
);

CREATE TABLE producto
(
    id_producto  BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    nombre       VARCHAR(255)                            NOT NULL,
    descripcion  VARCHAR(255),
    precio       DECIMAL                                 NOT NULL,
    stock        INTEGER                                 NOT NULL,
    stock_minimo INTEGER,
    id_categoria BIGINT,
    id_marca     BIGINT,
    created_at   TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    updated_at   TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_producto PRIMARY KEY (id_producto)
);

CREATE TABLE producto_atributo
(
    id_producto_atributo BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    id_producto          BIGINT                                  NOT NULL,
    id_atributo          BIGINT                                  NOT NULL,
    valor                VARCHAR(255)                            NOT NULL,
    created_at           TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    updated_at           TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_producto_atributo PRIMARY KEY (id_producto_atributo)
);

CREATE TABLE rol
(
    id_rol     BIGINT                      NOT NULL,
    nombre     VARCHAR(255)                NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_rol PRIMARY KEY (id_rol)
);

CREATE TABLE subastas
(
    id_subasta       BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    titulo           VARCHAR(150)                            NOT NULL,
    descripcion      TEXT,
    solo_vip         BOOLEAN                                 NOT NULL,
    precio_inicial   DECIMAL(10, 2)                          NOT NULL,
    duracion_minutos INTEGER                                 NOT NULL,
    estado           VARCHAR(30)                             NOT NULL,
    created_at       TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    updated_at       TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_subastas PRIMARY KEY (id_subasta)
);

CREATE TABLE usuario
(
    id_usuario      BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    nombre          VARCHAR(255),
    apellido        VARCHAR(255),
    email           VARCHAR(255),
    password        VARCHAR(255),
    es_vip          BOOLEAN,
    puntos_actuales INTEGER,
    id_rol          BIGINT,
    created_at      TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    updated_at      TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_usuario PRIMARY KEY (id_usuario)
);

CREATE TABLE valoracion
(
    id_valoracion BIGINT                      NOT NULL,
    id_usuario    BIGINT                      NOT NULL,
    id_producto   BIGINT                      NOT NULL,
    puntuacion    INTEGER                     NOT NULL,
    comentario    TEXT,
    created_at    TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    updated_at    TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_valoracion PRIMARY KEY (id_valoracion)
);

ALTER TABLE auditoria
    ADD CONSTRAINT FK_AUDITORIA_ON_ID_USUARIO FOREIGN KEY (id_usuario) REFERENCES usuario (id_usuario);

ALTER TABLE avisos
    ADD CONSTRAINT FK_AVISOS_ON_ID_USUARIO FOREIGN KEY (id_usuario) REFERENCES usuario (id_usuario);

ALTER TABLE carrito
    ADD CONSTRAINT FK_CARRITO_ON_ID_USUARIO FOREIGN KEY (id_usuario) REFERENCES usuario (id_usuario);

ALTER TABLE carrito_producto
    ADD CONSTRAINT FK_CARRITO_PRODUCTO_ON_ID_CARRITO FOREIGN KEY (id_carrito) REFERENCES carrito (id_carrito);

ALTER TABLE carrito_producto
    ADD CONSTRAINT FK_CARRITO_PRODUCTO_ON_ID_PRODUCTO FOREIGN KEY (id_producto) REFERENCES producto (id_producto);

ALTER TABLE direccion
    ADD CONSTRAINT FK_DIRECCION_ON_ID_USUARIO FOREIGN KEY (id_usuario) REFERENCES usuario (id_usuario);

ALTER TABLE imagen_categoria
    ADD CONSTRAINT FK_IMAGEN_CATEGORIA_ON_ID_CATEGORIA FOREIGN KEY (id_categoria) REFERENCES categoria (id_categoria);

ALTER TABLE imagen_categoria
    ADD CONSTRAINT FK_IMAGEN_CATEGORIA_ON_ID_IMAGEN FOREIGN KEY (id_imagen) REFERENCES imagen (id_imagen);

ALTER TABLE imagen_producto
    ADD CONSTRAINT FK_IMAGEN_PRODUCTO_ON_ID_IMAGEN FOREIGN KEY (id_imagen) REFERENCES imagen (id_imagen);

ALTER TABLE imagen_producto
    ADD CONSTRAINT FK_IMAGEN_PRODUCTO_ON_ID_PRODUCTO FOREIGN KEY (id_producto) REFERENCES producto (id_producto);

ALTER TABLE movimiento_puntos
    ADD CONSTRAINT FK_MOVIMIENTO_USUARIO FOREIGN KEY (id_usuario) REFERENCES usuario (id_usuario);

ALTER TABLE ofertas_subasta
    ADD CONSTRAINT FK_OFERTAS_SUBASTA_ON_ID_SUBASTA FOREIGN KEY (id_subasta) REFERENCES subastas (id_subasta);

ALTER TABLE ofertas_subasta
    ADD CONSTRAINT FK_OFERTAS_SUBASTA_ON_ID_USUARIO FOREIGN KEY (id_usuario) REFERENCES usuario (id_usuario);

ALTER TABLE pedidos
    ADD CONSTRAINT FK_PEDIDOS_ON_ID_USUARIO FOREIGN KEY (id_usuario) REFERENCES usuario (id_usuario);

ALTER TABLE pedido_producto
    ADD CONSTRAINT FK_PEDIDO_PRODUCTO_ON_PEDIDO FOREIGN KEY (pedido_id) REFERENCES pedidos (id_pedido);

ALTER TABLE pedido_producto
    ADD CONSTRAINT FK_PEDIDO_PRODUCTO_ON_PRODUCTO FOREIGN KEY (producto_id) REFERENCES producto (id_producto);

ALTER TABLE producto_atributo
    ADD CONSTRAINT FK_PRODUCTO_ATRIBUTO_ON_ID_ATRIBUTO FOREIGN KEY (id_atributo) REFERENCES atributo (id_atributo);

ALTER TABLE producto_atributo
    ADD CONSTRAINT FK_PRODUCTO_ATRIBUTO_ON_ID_PRODUCTO FOREIGN KEY (id_producto) REFERENCES producto (id_producto);

ALTER TABLE producto
    ADD CONSTRAINT FK_PRODUCTO_ON_ID_CATEGORIA FOREIGN KEY (id_categoria) REFERENCES categoria (id_categoria);

ALTER TABLE producto
    ADD CONSTRAINT FK_PRODUCTO_ON_ID_MARCA FOREIGN KEY (id_marca) REFERENCES marcas (id_marca);

ALTER TABLE usuario
    ADD CONSTRAINT FK_USUARIO_ON_ID_ROL FOREIGN KEY (id_rol) REFERENCES rol (id_rol);

ALTER TABLE valoracion
    ADD CONSTRAINT FK_VALORACION_ON_ID_PRODUCTO FOREIGN KEY (id_producto) REFERENCES producto (id_producto);

ALTER TABLE valoracion
    ADD CONSTRAINT FK_VALORACION_ON_ID_USUARIO FOREIGN KEY (id_usuario) REFERENCES usuario (id_usuario);